#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1' focus=on follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Code desktop='^3' focus=on follow=on
bspc rule -a Spotify desktop='^4' focus=on
bspc rule -a discord desktop='^5' focus=on follow=on
bspc rule -a Screenkey manage=off
